### ISSUE TITLE
Implement Transaction Builders

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/ruby-crypto#1]
See https://github.com/ArkEcosystem/php-crypto/tree/develop/src/Transactions for how the transaction builders were implemented.

**Comment by air1one** [comment]
Hi @faustbrian I see there is transaction builder code here lib/ark-crypto/transaction_builder.rb

So you mean you want to structure it the way it is in PHP, splitting it into different files and implementing what's missing ? Thanks.

**Comment by faustbrian** [comment]
Exactly, each transaction should be treated as its own entity instead of just having one big builder with `create*Transaction` methods.

**Comment by faustbrian** [comment]
@air1one Let me know if you send a PR so I can mark this as in progress.
