### ISSUE TITLE
Implement Message Signing

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/ruby-crypto#2]
See https://github.com/ArkEcosystem/php-crypto/blob/develop/src/Message.php for how message signing was implemented.

**Comment by air1one** [comment]
Hey @faustbrian I already did this in the previous repo, so now it's implemented in lib/ark-crypto/util/crypto.rb

**Comment by faustbrian** [comment]
Yeah but it needs some refactoring to look like the PHP implementation where the message is an object you can interact with 👀

**Comment by air1one** [comment]
Okayyy understood 👍

**Comment by faustbrian** [comment]
@air1one Let me know if you send a PR so I can mark this as in progress.

**Comment by air1one** [comment]
OK, I'm not working on it now, will have some time next week I'm keeping you updated.
